name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Upload Executable as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/TXTtoMediaWiki.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
